disabled_rules :
- line_length
- multiple_closures_with_trailing_closure
- trailing_newline
- trailing_whitespace
- mark
- comment_spacing
- operator_usage_whitespace
- closure_spacing
- implicitly_unwrapped_optional
- colon
#- SecretKey.swift
included :

identifier_name:
  allowed_symbols: "_"
 
 
opt_in_rules:
  - closure_spacing
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_multiple
  - legacy_random
  - operator_usage_whitespace
  
excluded:
- Pods
- Libraries
- AppAuth

